[build]
	publish = "exampleSite/public"
	command = "cd exampleSite && hugo --themesDir=../.. --baseURL $URL"

[context.production.environment]
	HUGO_VERSION = "0.140.1"
	HUGO_THEME = "repo"

[context.deploy-preview]
	command = "cd exampleSite && hugo --gc --themesDir ../.. --baseURL ${DEPLOY_PRIME_URL}"