baseURL = "https://example.com/"
languageCode = "en"
title = "Morandyt Demo" # website main title
theme = "morandyt"
defaultContentLanguage = "en"

[params]
    author = "Penyt"
    description = "hugo theme morandyt demo" # meta
    keywords = ["morandyt", "penyt", "hugo"] # meta

	themeColor = "morandi-blue"
	# Choices: morandi-red, morandi-orange, morandi-yellow, morandi-green, morandi-blue, morandi-indigo, morandi-purple,
	# red, orange, yellow, green, blue, indigo, purple, gray
	defaultColorMode = "dark" # Choices: light, dark


    [params.home]
        img = "img/bg.png"
        imgtitle = "IMG TITLE"
        imgdescription = "IMG DESCRIPTION"

        content = true # show content of content/_index.md

		allcategories = true # show all categories feature on the homepage

        allposts = true # show all posts feature on the homepage

    [params.footer]
        contact = "pen@penyt.com" # email
        startYear = "2024" # Can be empty

    [params.supports]
        likecoinID = "ytpenpen"
        buymeacoffeeID = "penyt"
        buymeacoffeeFont = ""
        buymeacoffeeFontColor = ""
        buymeacoffeeColor = "cyan"
        buymeacoffeeOutlineColor = ""
        buymeacoffeeCoffeeColor = ""
        buymeacoffeeText = "Buy me a Penguin"

    [params.comments]
        enable = true
        provider = "giscus"
        [params.comments.disqus]
            shortname = ""
        [params.comments.giscus]
            repo = "penyt/MyWebsite-comments" # change to your repo name
            repo_id = ""
            category = ""
            category_id = ""
            lightTheme = "light" # find giscus theme here: https://giscus.app
            darkTheme = "noborder_gray"

	[params.search]
		placeholder = "Search for anything..."

[permalinks]
    posts = "/p/:title/"

[pagination]
	pagerSize = 5

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 2

    [[menu.main]]
        name = "All Posts"
        url = "/posts/"
        weight = 3
    
    [[menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 4

    [[menu.main]]
        name = "Search"
        url = "/search/"
        weight = 5
    

[services]
    [services.googleAnalytics]
        id = ''

[taxonomies]
	tag = "tags"
	category = "categories"

[markup]
	[markup.highlight]
		noClasses = false
		guessSyntax = true
		style = "github-dark" # find styles here: https://gohugo.io/content-management/syntax-highlighting/#style
		lineNos = true
		lineNumbersInTable = true

	[markup.tableOfContents]
		startLevel = 2
		endLevel = 6

[outputs] # use for searching
	home = ["HTML", "RSS", "json"]