baseURL = "https://example.com/"
languageCode = "en" # for meta
title = "Morandyt Demo" # website main title
theme = "morandyt" # theme name
defaultContentLanguage = "en" # for theme language

[params]
    author = "Penyt" # meta & footer
    description = "hugo theme morandyt demo" # meta
    keywords = ["morandyt", "penyt", "hugo"] # meta

	themeColor = "morandi-blue"
	# Choices: 
	# 	morandi-red, morandi-orange, morandi-yellow, morandi-green, morandi-blue, morandi-indigo, morandi-purple,
	# 	red, orange, yellow, green, blue, indigo, purple, gray

	defaultColorMode = "dark" # Choices: light, dark


    [params.home]
        img = "img/bg.png" # static/img/bg.png
        imgtitle = "IMG TITLE"
        imgdescription = "IMG DESCRIPTION"

        content = true # show content of content/_index.md

		features = true # show feature section on the homepage

		allcategories = true # show all categories section on the homepage

        allposts = true # show all posts section on the homepage

    [params.footer]
        contact = "pen@penyt.com" # email
        startYear = "2024" # Can be empty
		authorImage = "img/penlike.png" # static/img/author.png

    [params.supports]
        likecoinID = "ytpenpen"
		
        buymeacoffeeID = "penyt"
        buymeacoffeeFont = ""
        buymeacoffeeFontColor = ""
        buymeacoffeeColor = "cyan"
        buymeacoffeeOutlineColor = ""
        buymeacoffeeCoffeeColor = ""
        buymeacoffeeText = "Buy me a Penguin"

    [params.comments]
        enable = true
        provider = "giscus" # morandyt now supports  disqus & giscus
        [params.comments.disqus]
            shortname = ""
        [params.comments.giscus]
            repo = "penyt/MyWebsite-comments" # put your repo name
            repo_id = ""
            category = ""
            category_id = ""
            lightTheme = "light" # find giscus theme here: https://giscus.app
            darkTheme = "noborder_gray"

	[params.search]
		placeholder = "Search for anything..."

[permalinks]
    posts = "/p/:title/"

[pagination]
	pagerSize = 3

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 2

    [[menu.main]]
        name = "All Posts"
        url = "/posts/"
        weight = 3
    
    [[menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 4

    [[menu.main]]
        name = "Search"
        url = "/search/"
        weight = 5
    

[taxonomies] # recommend not to change
	tag = "tags"
	category = "categories"

[markup]
	[markup.highlight] # style of code block in md
		noClasses = false
		guessSyntax = true
		# Morandyt uses chroma-<light/dark>.css, so no style is required here.
		# style = "github-dark" # find styles here: https://gohugo.io/content-management/syntax-highlighting/#style
		lineNos = true
		lineNumbersInTable = true

	[markup.tableOfContents]
		startLevel = 2
		endLevel = 6

[outputs] # use for searching, recommend not to change
	home = ["HTML", "RSS", "json"]